/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "DateInterval".
 */
export type DateInterval1 = Interval1 & DateInterval;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Interval".
 */
export type Interval1 = Any & Interval;
export type LowClosed = Boolean1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Boolean".
 */
export type Boolean1 = Any & Boolean;
export type Value = boolean | null;
export type HighClosed = Boolean1;
export type Low = Date1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Date".
 */
export type Date1 = Any & Date;
export type Value1 = string | null;
export type High = Date1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "DiagnosticStudyRecommended".
 */
export type DiagnosticStudyRecommended1 = QDMBaseType & DiagnosticStudyRecommended;
export type Id1 = Id;
export type NamingSystem = String1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "String".
 */
export type String1 = Any & String;
export type Value2 = string | null;
export type Value3 = String1;
export type Code3 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Code".
 */
export type Code2 = Any & Code;
export type Code1 = String1;
export type Display = String1;
export type System = String1;
export type Version = String1;
export type PatientId = Id;
export type Reporter = Id;
export type Recorder = Id;
export type AuthorDatetime = DateTime1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "DateTime".
 */
export type DateTime1 = Any & DateTime;
export type Value4 = string | null;
export type NegationRationale = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "EncounterPerformed".
 */
export type EncounterPerformed1 = QDMBaseType & EncounterPerformed;
export type AuthorDatetime1 = DateTime1;
export type AdmissionSource = Code2;
export type RelevantPeriod = DateTimeInterval1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "DateTimeInterval".
 */
export type DateTimeInterval1 = Interval1 & DateTimeInterval;
export type Low1 = DateTime1;
export type High1 = DateTime1;
export type DischargeDisposition = Code2;
export type Diagnosis = Code2[];
export type FacilityLocation1 = FacilityLocation[];
export type Code4 = Code2;
export type LocationPeriod = DateTimeInterval1;
export type PrincipalDiagnosis = Code2;
export type NegationRationale1 = Code2;
export type LengthOfStay = Quantity1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Quantity".
 */
export type Quantity1 = Any & Quantity;
export type Value6 = Decimal1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Decimal".
 */
export type Decimal1 = Any & Decimal;
export type Value5 = number | null;
export type Unit = String1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "IntegerInterval".
 */
export type IntegerInterval1 = Interval1 & IntegerInterval;
export type Low2 = Integer1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Integer".
 */
export type Integer1 = Any & Integer;
export type Value7 = number | null;
export type High2 = Integer1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "SubstanceAdministered".
 */
export type SubstanceAdministered1 = QDMBaseType & SubstanceAdministered;
export type AuthorDatetime2 = DateTime1;
export type RelevantPeriod1 = DateTimeInterval1;
export type Dosage = Quantity1;
export type Frequency = Code2;
export type Route = Code2;
export type NegationRationale2 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "MedicationDispensed".
 */
export type MedicationDispensed1 = QDMBaseType & MedicationDispensed;
export type AuthorDatetime3 = DateTime1;
export type RelevantPeriod2 = DateTimeInterval1;
export type Refills = number | null;
export type Dosage1 = Quantity1;
export type Supply = Quantity1;
export type Frequency1 = Code2;
export type DaysSupplied = Integer1;
export type Route1 = Code2;
export type PrescriberId = Id;
export type DispenserId = Id;
export type NegationRationale3 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "AssessmentOrder".
 */
export type AssessmentOrder1 = QDMBaseType & AssessmentOrder;
export type AuthorDatetime4 = DateTime1;
export type NegationRationale4 = Code2;
export type Reason = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "ImmunizationAdministered".
 */
export type ImmunizationAdministered1 = QDMBaseType & ImmunizationAdministered;
export type AuthorDatetime5 = DateTime1;
export type Dosage2 = Quantity1;
export type Reason1 = Code2;
export type Route2 = Code2;
export type NegationRationale5 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "InterventionRecommended".
 */
export type InterventionRecommended1 = QDMBaseType & InterventionRecommended;
export type AuthorDatetime6 = DateTime1;
export type Reason2 = Code2;
export type NegationRationale6 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "ProcedureOrder".
 */
export type ProcedureOrder1 = QDMBaseType & ProcedureOrder;
export type AuthorDatetime7 = DateTime1;
export type Reason3 = Code2;
export type AnatomicalLocationSite = Code2;
export type Ordinality = Code2;
export type NegationRationale7 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "ProviderCharacteristic".
 */
export type ProviderCharacteristic1 = QDMBaseType & ProviderCharacteristic;
export type AuthorDatetime8 = DateTime1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "DeviceApplied".
 */
export type DeviceApplied1 = QDMBaseType & DeviceApplied;
export type AuthorDatetime9 = DateTime1;
export type RelevantPeriod3 = DateTimeInterval1;
export type NegationRationale8 = Code2;
export type Reason4 = Code2;
export type AnatomicalLocationSite1 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "LaboratoryTestRecommended".
 */
export type LaboratoryTestRecommended1 = QDMBaseType & LaboratoryTestRecommended;
export type AuthorDatetime10 = DateTime1;
export type Reason5 = Code2;
export type NegationRationale9 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "PhysicalExamPerformed".
 */
export type PhysicalExamPerformed1 = QDMBaseType & PhysicalExamPerformed;
export type AuthorDatetime11 = DateTime1;
export type RelevantPeriod4 = DateTimeInterval1;
export type Reason6 = Code2;
export type Method = Code2;
export type Result = Any;
export type AnatomicalLocationSite2 = Code2;
export type NegationRationale10 = Code2;
export type Component1 = Component[];
export type Code5 = Code2;
export type Result1 = Any;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "DeviceOrder".
 */
export type DeviceOrder1 = QDMBaseType & DeviceOrder;
export type AuthorDatetime12 = DateTime1;
export type NegationRationale11 = Code2;
export type Reason7 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "LaboratoryTestPerformed".
 */
export type LaboratoryTestPerformed1 = QDMBaseType & LaboratoryTestPerformed;
export type AuthorDatetime13 = DateTime1;
export type RelevantPeriod5 = DateTimeInterval1;
export type Status = Code2;
export type Method1 = Code2;
export type Result2 = Any;
export type ResultDatetime = DateTime1;
export type Reason8 = Code2;
export type ReferenceRange = QuantityInterval1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "QuantityInterval".
 */
export type QuantityInterval1 = Interval1 & QuantityInterval;
export type Low3 = Quantity1;
export type High3 = Quantity1;
export type NegationRationale12 = Code2;
export type Component2 = Component[];
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Time".
 */
export type Time1 = Any & Time;
export type Value8 = string | null;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "TimeInterval".
 */
export type TimeInterval1 = Interval1 & TimeInterval;
export type Low4 = Time1;
export type High4 = Time1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "PatientCharacteristic".
 */
export type PatientCharacteristic1 = QDMBaseType & PatientCharacteristic;
export type AuthorDatetime14 = DateTime1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "PatientCharacteristicRace".
 */
export type PatientCharacteristicRace1 = QDMBaseType & PatientCharacteristicRace;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "PatientCharacteristicClinicalTrialParticipant".
 */
export type PatientCharacteristicClinicalTrialParticipant1 = QDMBaseType &
  PatientCharacteristicClinicalTrialParticipant;
export type Reason9 = Code2;
export type RelevantPeriod6 = DateTimeInterval1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "ProviderCareExperience".
 */
export type ProviderCareExperience1 = QDMBaseType & ProviderCareExperience;
export type AuthorDatetime15 = DateTime1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "EncounterRecommended".
 */
export type EncounterRecommended1 = QDMBaseType & EncounterRecommended;
export type AuthorDatetime16 = DateTime1;
export type Reason10 = Code2;
export type FacilityLocation2 = Code2;
export type NegationRationale13 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "CommunicationPerformed".
 */
export type CommunicationPerformed1 = QDMBaseType & CommunicationPerformed;
export type AuthorDatetime17 = DateTime1;
export type Category = Code2;
export type Medium = Code2;
export type Sender = Code2;
export type Recipient = Code2;
export type RelevantPeriod7 = DateTimeInterval1;
export type NegationRationale14 = Code2;
export type RelatedTo = Id[];
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Diagnosis".
 */
export type Diagnosis2 = QDMBaseType & Diagnosis1;
export type AuthorDatetime18 = DateTime1;
export type PrevalencePeriod = DateTimeInterval1;
export type AnatomicalLocationSite3 = Code2;
export type Severity = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "PhysicalExamRecommended".
 */
export type PhysicalExamRecommended1 = QDMBaseType & PhysicalExamRecommended;
export type AuthorDatetime19 = DateTime1;
export type Reason11 = Code2;
export type AnatomicalLocationSite4 = Code2;
export type NegationRationale15 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "LaboratoryTestOrder".
 */
export type LaboratoryTestOrder1 = QDMBaseType & LaboratoryTestOrder;
export type AuthorDatetime20 = DateTime1;
export type Reason12 = Code2;
export type NegationRationale16 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "MedicationActive".
 */
export type MedicationActive1 = QDMBaseType & MedicationActive;
export type RelevantPeriod8 = DateTimeInterval1;
export type Dosage3 = Quantity1;
export type Frequency2 = Code2;
export type Route3 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "MedicationDischarge".
 */
export type MedicationDischarge1 = QDMBaseType & MedicationDischarge;
export type AuthorDatetime21 = DateTime1;
export type Refills1 = number | null;
export type Dosage4 = Quantity1;
export type Supply1 = Quantity1;
export type Frequency3 = Code2;
export type DaysSupplied1 = Integer1;
export type Route4 = Code2;
export type NegationRationale17 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Participation".
 */
export type Participation1 = QDMBaseType & Participation;
export type ParticipationPeriod = DateTimeInterval1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Ratio".
 */
export type Ratio1 = Any & Ratio;
export type Numerator = Quantity1;
export type Denominator = Quantity1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "PatientCharacteristicPayer".
 */
export type PatientCharacteristicPayer1 = QDMBaseType & PatientCharacteristicPayer;
export type RelevantPeriod9 = DateTimeInterval1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "PatientCharacteristicSex".
 */
export type PatientCharacteristicSex1 = QDMBaseType & PatientCharacteristicSex;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "InterventionPerformed".
 */
export type InterventionPerformed1 = QDMBaseType & InterventionPerformed;
export type AuthorDatetime22 = DateTime1;
export type RelevantPeriod10 = DateTimeInterval1;
export type Reason13 = Code2;
export type Result3 = Any;
export type Status1 = Code2;
export type NegationRationale18 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "DiagnosticStudyOrder".
 */
export type DiagnosticStudyOrder1 = QDMBaseType & DiagnosticStudyOrder;
export type AuthorDatetime23 = DateTime1;
export type Reason14 = Code2;
export type NegationRationale19 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "FamilyHistory".
 */
export type FamilyHistory1 = QDMBaseType & FamilyHistory;
export type AuthorDatetime24 = DateTime1;
export type Relationship = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "PatientCharacteristicBirthdate".
 */
export type PatientCharacteristicBirthdate1 = QDMBaseType & PatientCharacteristicBirthdate;
export type BirthDatetime = DateTime1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "AllergyIntolerance".
 */
export type AllergyIntolerance1 = QDMBaseType & AllergyIntolerance;
export type AuthorDatetime25 = DateTime1;
export type PrevalencePeriod1 = DateTimeInterval1;
export type Type = Code2;
export type Severity1 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "DeviceRecommended".
 */
export type DeviceRecommended1 = QDMBaseType & DeviceRecommended;
export type AuthorDatetime26 = DateTime1;
export type NegationRationale20 = Code2;
export type Reason15 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "SubstanceOrder".
 */
export type SubstanceOrder1 = QDMBaseType & SubstanceOrder;
export type AuthorDatetime27 = DateTime1;
export type Reason16 = Code2;
export type Dosage5 = Quantity1;
export type Supply2 = Quantity1;
export type Frequency4 = Code2;
export type Refills2 = number | null;
export type Route5 = Code2;
export type NegationRationale21 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "AssessmentPerformed".
 */
export type AssessmentPerformed1 = QDMBaseType & AssessmentPerformed;
export type AuthorDatetime28 = DateTime1;
export type NegationRationale22 = Code2;
export type Reason17 = Code2;
export type Method2 = Code2;
export type Result4 = Any;
export type Component3 = Component[];
export type RelatedTo1 = Id[];
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "EncounterOrder".
 */
export type EncounterOrder1 = QDMBaseType & EncounterOrder;
export type AuthorDatetime29 = DateTime1;
export type Reason18 = Code2;
export type FacilityLocation3 = Code2;
export type NegationRationale23 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "ProcedurePerformed".
 */
export type ProcedurePerformed1 = QDMBaseType & ProcedurePerformed;
export type AuthorDatetime30 = DateTime1;
export type RelevantPeriod11 = DateTimeInterval1;
export type Reason19 = Code2;
export type Method3 = Code2;
export type Result5 = Any;
export type Status2 = Code2;
export type AnatomicalLocationSite5 = Code2;
export type Ordinality1 = Code2;
export type IncisionDatetime = DateTime1;
export type NegationRationale24 = Code2;
export type Component4 = Component[];
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "DiagnosticStudyPerformed".
 */
export type DiagnosticStudyPerformed1 = QDMBaseType & DiagnosticStudyPerformed;
export type AuthorDatetime31 = DateTime1;
export type RelevantPeriod12 = DateTimeInterval1;
export type Reason20 = Code2;
export type Result6 = Any;
export type ResultDatetime1 = DateTime1;
export type Status3 = Code2;
export type Method4 = Code2;
export type FacilityLocation4 = Code2;
export type NegationRationale25 = Code2;
export type Component5 = Component[];
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "PatientCharacteristicEthnicity".
 */
export type PatientCharacteristicEthnicity1 = QDMBaseType & PatientCharacteristicEthnicity;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "AssessmentRecommended".
 */
export type AssessmentRecommended1 = QDMBaseType & AssessmentRecommended;
export type AuthorDatetime32 = DateTime1;
export type NegationRationale26 = Code2;
export type Reason21 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "PhysicalExamOrder".
 */
export type PhysicalExamOrder1 = QDMBaseType & PhysicalExamOrder;
export type AuthorDatetime33 = DateTime1;
export type Reason22 = Code2;
export type AnatomicalLocationSite6 = Code2;
export type NegationRationale27 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "CareGoal".
 */
export type CareGoal1 = QDMBaseType & CareGoal;
export type RelevantPeriod13 = DateTimeInterval1;
export type RelatedTo2 = Id[];
export type TargetOutcome = Any;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "ProcedureRecommended".
 */
export type ProcedureRecommended1 = QDMBaseType & ProcedureRecommended;
export type AuthorDatetime34 = DateTime1;
export type Reason23 = Code2;
export type AnatomicalLocationSite7 = Code2;
export type Ordinality2 = Code2;
export type NegationRationale28 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "MedicationAdministered".
 */
export type MedicationAdministered1 = QDMBaseType & MedicationAdministered;
export type AuthorDatetime35 = DateTime1;
export type RelevantPeriod14 = DateTimeInterval1;
export type Dosage6 = Quantity1;
export type Frequency5 = Code2;
export type Route6 = Code2;
export type Reason24 = Code2;
export type NegationRationale29 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "SubstanceRecommended".
 */
export type SubstanceRecommended1 = QDMBaseType & SubstanceRecommended;
export type AuthorDatetime36 = DateTime1;
export type Reason25 = Code2;
export type Dosage7 = Quantity1;
export type Frequency6 = Code2;
export type Refills3 = number | null;
export type Route7 = Code2;
export type NegationRationale30 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Symptom".
 */
export type Symptom1 = QDMBaseType & Symptom;
export type PrevalencePeriod2 = DateTimeInterval1;
export type Severity2 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "DecimalInterval".
 */
export type DecimalInterval1 = Interval1 & DecimalInterval;
export type Low5 = Decimal1;
export type High5 = Decimal1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "MedicationOrder".
 */
export type MedicationOrder1 = QDMBaseType & MedicationOrder;
export type AuthorDatetime37 = DateTime1;
export type RelevantPeriod15 = DateTimeInterval1;
export type Refills4 = number | null;
export type Dosage8 = Quantity1;
export type Supply3 = Quantity1;
export type Frequency7 = Code2;
export type DaysSupplied2 = Integer1;
export type Route8 = Code2;
export type Setting = Code2;
export type Reason26 = Code2;
export type PrescriberId1 = Id;
export type NegationRationale31 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "PatientCareExperience".
 */
export type PatientCareExperience1 = QDMBaseType & PatientCareExperience;
export type AuthorDatetime38 = DateTime1;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "ImmunizationOrder".
 */
export type ImmunizationOrder1 = QDMBaseType & ImmunizationOrder;
export type ActiveDatetime = DateTime1;
export type AuthorDatetime39 = DateTime1;
export type Dosage9 = Quantity1;
export type Reason27 = Code2;
export type Route9 = Code2;
export type NegationRationale32 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "PatientCharacteristicExpired".
 */
export type PatientCharacteristicExpired1 = QDMBaseType & PatientCharacteristicExpired;
export type ExpiredDatetime = DateTime1;
export type Cause = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "AdverseEvent".
 */
export type AdverseEvent1 = QDMBaseType & AdverseEvent;
export type AuthorDatetime40 = DateTime1;
export type RelevantPeriod16 = DateTimeInterval1;
export type Severity3 = Code2;
export type FacilityLocation5 = Code2;
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "InterventionOrder".
 */
export type InterventionOrder1 = QDMBaseType & InterventionOrder;
export type AuthorDatetime41 = DateTime1;
export type Reason28 = Code2;
export type NegationRationale33 = Code2;
export type Codes = Code2[];
export type Display1 = String1;

export interface UrnHealthitGovQdmV5_4 {
  [k: string]: any;
}
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Any".
 */
export interface Any {
  [k: string]: any;
}
export interface Interval {
  lowClosed?: LowClosed;
  highClosed?: HighClosed;
  [k: string]: any;
}
export interface Boolean {
  value?: Value;
  [k: string]: any;
}
export interface DateInterval {
  low?: Low;
  high?: High;
  [k: string]: any;
}
export interface Date {
  value?: Value1;
  [k: string]: any;
}
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "QDMBaseType".
 */
export interface QDMBaseType {
  id: Id1;
  code: Code3;
  patientId: PatientId;
  reporter?: Reporter;
  recorder?: Recorder;
  [k: string]: any;
}
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Id".
 */
export interface Id {
  namingSystem?: NamingSystem;
  value: Value3;
  [k: string]: any;
}
export interface String {
  value?: Value2;
  [k: string]: any;
}
export interface Code {
  code?: Code1;
  display?: Display;
  system?: System;
  version?: Version;
  [k: string]: any;
}
export interface DiagnosticStudyRecommended {
  authorDatetime?: AuthorDatetime;
  negationRationale?: NegationRationale;
  [k: string]: any;
}
export interface DateTime {
  value?: Value4;
  [k: string]: any;
}
export interface EncounterPerformed {
  authorDatetime?: AuthorDatetime1;
  admissionSource?: AdmissionSource;
  relevantPeriod?: RelevantPeriod;
  dischargeDisposition?: DischargeDisposition;
  diagnosis?: Diagnosis;
  facilityLocation?: FacilityLocation1;
  principalDiagnosis?: PrincipalDiagnosis;
  negationRationale?: NegationRationale1;
  lengthOfStay?: LengthOfStay;
  [k: string]: any;
}
export interface DateTimeInterval {
  low?: Low1;
  high?: High1;
  [k: string]: any;
}
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "FacilityLocation".
 */
export interface FacilityLocation {
  code: Code4;
  locationPeriod?: LocationPeriod;
  [k: string]: any;
}
export interface Quantity {
  value?: Value6;
  unit?: Unit;
  [k: string]: any;
}
export interface Decimal {
  value?: Value5;
  [k: string]: any;
}
export interface IntegerInterval {
  low?: Low2;
  high?: High2;
  [k: string]: any;
}
export interface Integer {
  value?: Value7;
  [k: string]: any;
}
export interface SubstanceAdministered {
  authorDatetime?: AuthorDatetime2;
  relevantPeriod?: RelevantPeriod1;
  dosage?: Dosage;
  frequency?: Frequency;
  route?: Route;
  negationRationale?: NegationRationale2;
  [k: string]: any;
}
export interface MedicationDispensed {
  authorDatetime?: AuthorDatetime3;
  relevantPeriod?: RelevantPeriod2;
  refills?: Refills;
  dosage?: Dosage1;
  supply?: Supply;
  frequency?: Frequency1;
  daysSupplied?: DaysSupplied;
  route?: Route1;
  prescriberId?: PrescriberId;
  dispenserId?: DispenserId;
  negationRationale?: NegationRationale3;
  [k: string]: any;
}
export interface AssessmentOrder {
  authorDatetime?: AuthorDatetime4;
  negationRationale?: NegationRationale4;
  reason?: Reason;
  [k: string]: any;
}
export interface ImmunizationAdministered {
  authorDatetime?: AuthorDatetime5;
  dosage?: Dosage2;
  reason?: Reason1;
  route?: Route2;
  negationRationale?: NegationRationale5;
  [k: string]: any;
}
export interface InterventionRecommended {
  authorDatetime?: AuthorDatetime6;
  reason?: Reason2;
  negationRationale?: NegationRationale6;
  [k: string]: any;
}
export interface ProcedureOrder {
  authorDatetime?: AuthorDatetime7;
  reason?: Reason3;
  anatomicalLocationSite?: AnatomicalLocationSite;
  ordinality?: Ordinality;
  negationRationale?: NegationRationale7;
  [k: string]: any;
}
export interface ProviderCharacteristic {
  authorDatetime?: AuthorDatetime8;
  [k: string]: any;
}
export interface DeviceApplied {
  authorDatetime?: AuthorDatetime9;
  relevantPeriod?: RelevantPeriod3;
  negationRationale?: NegationRationale8;
  reason?: Reason4;
  anatomicalLocationSite?: AnatomicalLocationSite1;
  [k: string]: any;
}
export interface LaboratoryTestRecommended {
  authorDatetime?: AuthorDatetime10;
  reason?: Reason5;
  negationRationale?: NegationRationale9;
  [k: string]: any;
}
export interface PhysicalExamPerformed {
  authorDatetime?: AuthorDatetime11;
  relevantPeriod?: RelevantPeriod4;
  reason?: Reason6;
  method?: Method;
  result?: Result;
  anatomicalLocationSite?: AnatomicalLocationSite2;
  negationRationale?: NegationRationale10;
  component?: Component1;
  [k: string]: any;
}
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Component".
 */
export interface Component {
  code: Code5;
  result?: Result1;
  [k: string]: any;
}
export interface DeviceOrder {
  authorDatetime?: AuthorDatetime12;
  negationRationale?: NegationRationale11;
  reason?: Reason7;
  [k: string]: any;
}
export interface LaboratoryTestPerformed {
  authorDatetime?: AuthorDatetime13;
  relevantPeriod?: RelevantPeriod5;
  status?: Status;
  method?: Method1;
  result?: Result2;
  resultDatetime?: ResultDatetime;
  reason?: Reason8;
  referenceRange?: ReferenceRange;
  negationRationale?: NegationRationale12;
  component?: Component2;
  [k: string]: any;
}
export interface QuantityInterval {
  low?: Low3;
  high?: High3;
  [k: string]: any;
}
export interface Time {
  value?: Value8;
  [k: string]: any;
}
export interface TimeInterval {
  low?: Low4;
  high?: High4;
  [k: string]: any;
}
export interface PatientCharacteristic {
  authorDatetime?: AuthorDatetime14;
  [k: string]: any;
}
export interface PatientCharacteristicRace {
  [k: string]: any;
}
export interface PatientCharacteristicClinicalTrialParticipant {
  reason?: Reason9;
  relevantPeriod?: RelevantPeriod6;
  [k: string]: any;
}
export interface ProviderCareExperience {
  authorDatetime?: AuthorDatetime15;
  [k: string]: any;
}
export interface EncounterRecommended {
  authorDatetime?: AuthorDatetime16;
  reason?: Reason10;
  facilityLocation?: FacilityLocation2;
  negationRationale?: NegationRationale13;
  [k: string]: any;
}
export interface CommunicationPerformed {
  authorDatetime?: AuthorDatetime17;
  category?: Category;
  medium?: Medium;
  sender?: Sender;
  recipient?: Recipient;
  relevantPeriod?: RelevantPeriod7;
  negationRationale?: NegationRationale14;
  relatedTo?: RelatedTo;
  [k: string]: any;
}
export interface Diagnosis1 {
  authorDatetime?: AuthorDatetime18;
  prevalencePeriod?: PrevalencePeriod;
  anatomicalLocationSite?: AnatomicalLocationSite3;
  severity?: Severity;
  [k: string]: any;
}
export interface PhysicalExamRecommended {
  authorDatetime?: AuthorDatetime19;
  reason?: Reason11;
  anatomicalLocationSite?: AnatomicalLocationSite4;
  negationRationale?: NegationRationale15;
  [k: string]: any;
}
export interface LaboratoryTestOrder {
  authorDatetime?: AuthorDatetime20;
  reason?: Reason12;
  negationRationale?: NegationRationale16;
  [k: string]: any;
}
export interface MedicationActive {
  relevantPeriod?: RelevantPeriod8;
  dosage?: Dosage3;
  frequency?: Frequency2;
  route?: Route3;
  [k: string]: any;
}
export interface MedicationDischarge {
  authorDatetime?: AuthorDatetime21;
  refills?: Refills1;
  dosage?: Dosage4;
  supply?: Supply1;
  frequency?: Frequency3;
  daysSupplied?: DaysSupplied1;
  route?: Route4;
  negationRationale?: NegationRationale17;
  [k: string]: any;
}
export interface Participation {
  participationPeriod?: ParticipationPeriod;
  [k: string]: any;
}
export interface Ratio {
  numerator?: Numerator;
  denominator?: Denominator;
  [k: string]: any;
}
export interface PatientCharacteristicPayer {
  relevantPeriod?: RelevantPeriod9;
  [k: string]: any;
}
export interface PatientCharacteristicSex {
  [k: string]: any;
}
export interface InterventionPerformed {
  authorDatetime?: AuthorDatetime22;
  relevantPeriod?: RelevantPeriod10;
  reason?: Reason13;
  result?: Result3;
  status?: Status1;
  negationRationale?: NegationRationale18;
  [k: string]: any;
}
export interface DiagnosticStudyOrder {
  authorDatetime?: AuthorDatetime23;
  reason?: Reason14;
  negationRationale?: NegationRationale19;
  [k: string]: any;
}
export interface FamilyHistory {
  authorDatetime?: AuthorDatetime24;
  relationship?: Relationship;
  [k: string]: any;
}
export interface PatientCharacteristicBirthdate {
  birthDatetime?: BirthDatetime;
  [k: string]: any;
}
export interface AllergyIntolerance {
  authorDatetime?: AuthorDatetime25;
  prevalencePeriod?: PrevalencePeriod1;
  type?: Type;
  severity?: Severity1;
  [k: string]: any;
}
export interface DeviceRecommended {
  authorDatetime?: AuthorDatetime26;
  negationRationale?: NegationRationale20;
  reason?: Reason15;
  [k: string]: any;
}
export interface SubstanceOrder {
  authorDatetime?: AuthorDatetime27;
  reason?: Reason16;
  dosage?: Dosage5;
  supply?: Supply2;
  frequency?: Frequency4;
  refills?: Refills2;
  route?: Route5;
  negationRationale?: NegationRationale21;
  [k: string]: any;
}
export interface AssessmentPerformed {
  authorDatetime?: AuthorDatetime28;
  negationRationale?: NegationRationale22;
  reason?: Reason17;
  method?: Method2;
  result?: Result4;
  component?: Component3;
  relatedTo?: RelatedTo1;
  [k: string]: any;
}
export interface EncounterOrder {
  authorDatetime?: AuthorDatetime29;
  reason?: Reason18;
  facilityLocation?: FacilityLocation3;
  negationRationale?: NegationRationale23;
  [k: string]: any;
}
export interface ProcedurePerformed {
  authorDatetime?: AuthorDatetime30;
  relevantPeriod?: RelevantPeriod11;
  reason?: Reason19;
  method?: Method3;
  result?: Result5;
  status?: Status2;
  anatomicalLocationSite?: AnatomicalLocationSite5;
  ordinality?: Ordinality1;
  incisionDatetime?: IncisionDatetime;
  negationRationale?: NegationRationale24;
  component?: Component4;
  [k: string]: any;
}
export interface DiagnosticStudyPerformed {
  authorDatetime?: AuthorDatetime31;
  relevantPeriod?: RelevantPeriod12;
  reason?: Reason20;
  result?: Result6;
  resultDatetime?: ResultDatetime1;
  status?: Status3;
  method?: Method4;
  facilityLocation?: FacilityLocation4;
  negationRationale?: NegationRationale25;
  component?: Component5;
  [k: string]: any;
}
export interface PatientCharacteristicEthnicity {
  [k: string]: any;
}
export interface AssessmentRecommended {
  authorDatetime?: AuthorDatetime32;
  negationRationale?: NegationRationale26;
  reason?: Reason21;
  [k: string]: any;
}
export interface PhysicalExamOrder {
  authorDatetime?: AuthorDatetime33;
  reason?: Reason22;
  anatomicalLocationSite?: AnatomicalLocationSite6;
  negationRationale?: NegationRationale27;
  [k: string]: any;
}
export interface CareGoal {
  relevantPeriod?: RelevantPeriod13;
  relatedTo?: RelatedTo2;
  targetOutcome?: TargetOutcome;
  [k: string]: any;
}
export interface ProcedureRecommended {
  authorDatetime?: AuthorDatetime34;
  reason?: Reason23;
  anatomicalLocationSite?: AnatomicalLocationSite7;
  ordinality?: Ordinality2;
  negationRationale?: NegationRationale28;
  [k: string]: any;
}
export interface MedicationAdministered {
  authorDatetime?: AuthorDatetime35;
  relevantPeriod?: RelevantPeriod14;
  dosage?: Dosage6;
  frequency?: Frequency5;
  route?: Route6;
  reason?: Reason24;
  negationRationale?: NegationRationale29;
  [k: string]: any;
}
export interface SubstanceRecommended {
  authorDatetime?: AuthorDatetime36;
  reason?: Reason25;
  dosage?: Dosage7;
  frequency?: Frequency6;
  refills?: Refills3;
  route?: Route7;
  negationRationale?: NegationRationale30;
  [k: string]: any;
}
export interface Symptom {
  prevalencePeriod?: PrevalencePeriod2;
  severity?: Severity2;
  [k: string]: any;
}
export interface DecimalInterval {
  low?: Low5;
  high?: High5;
  [k: string]: any;
}
export interface MedicationOrder {
  authorDatetime?: AuthorDatetime37;
  relevantPeriod?: RelevantPeriod15;
  refills?: Refills4;
  dosage?: Dosage8;
  supply?: Supply3;
  frequency?: Frequency7;
  daysSupplied?: DaysSupplied2;
  route?: Route8;
  setting?: Setting;
  reason?: Reason26;
  prescriberId?: PrescriberId1;
  negationRationale?: NegationRationale31;
  [k: string]: any;
}
export interface PatientCareExperience {
  authorDatetime?: AuthorDatetime38;
  [k: string]: any;
}
export interface ImmunizationOrder {
  activeDatetime?: ActiveDatetime;
  authorDatetime?: AuthorDatetime39;
  dosage?: Dosage9;
  reason?: Reason27;
  route?: Route9;
  negationRationale?: NegationRationale32;
  [k: string]: any;
}
export interface PatientCharacteristicExpired {
  expiredDatetime?: ExpiredDatetime;
  cause?: Cause;
  [k: string]: any;
}
export interface AdverseEvent {
  authorDatetime?: AuthorDatetime40;
  relevantPeriod?: RelevantPeriod16;
  severity?: Severity3;
  facilityLocation?: FacilityLocation5;
  [k: string]: any;
}
export interface InterventionOrder {
  authorDatetime?: AuthorDatetime41;
  reason?: Reason28;
  negationRationale?: NegationRationale33;
  [k: string]: any;
}
/**
 * This interface was referenced by `UrnHealthitGovQdmV5_4`'s JSON-Schema
 * via the `definition` "Concept".
 */
export interface Concept {
  codes: Codes;
  display?: Display1;
  [k: string]: any;
}
